plugins {
    id 'com.android.application'
}

android {
    namespace 'es.mcd3.lunapanoshooter'
    compileSdk 35

    defaultConfig {
        applicationId 'es.mcd3.lunapanoshooter'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0-beta'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
